export default {
  baseUrl: "/v1",
  CONFIG_FETCH: "CONFIG_FETCH",
  CONFIG_SET:   "CONFIG_SET",
  TOY_FETCH_ALL: "TOY_FETCH_ALL",
  TOY_FETCH:     "TOY_FETCH",
  TOY_CREATE:    "TOY_CREATE",
  TOY_MODIFY:    "TOY_MODIFY",
  TOY_DELETE:    "TOY_DELETE",
  ERROR:         "ERROR"
};
